### ISSUE TITLE
Build failed on VS 10

### ISSUE THREAD

**Issue by souaremsaidou** [troian/jwtpp#30]
**Configure project**
`$ full/path/to/cmake-3.17.0/bin/cmake.exe -G "Visual Studio 10" .. - DCMAKE_INSTALL_PREFIX:PATH="full/path/to/install/dir/jwt" -DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DJsonCPP_INCLUDE_DIRS "full/path/to/jsoncpp/include/jsoncpp" -DJsonCPP_LIBRARIES "full/path/to/jsoncpp/lib/jsoncpp.lib"`

![image](https://user-images.githubusercontent.com/57505334/75361527-b8bee880-58b7-11ea-8c3f-3b31a3e2d894.png)

**Additional Dependencies**

> 1. jsoncpp [build succeed] with Visual Studio Code 10 and produces:
> 7>Build succeeded.
> 7>
> 7>Time Elapsed 00:00:09.40
> 9>------ Skipped Build: Project: jsoncpp_check, Configuration: Debug Win32 ------
> 9>Project not selected to build for this solution configuration 
> ========== Build: 6 succeeded, 0 failed, 0 up-to-date, 3 skipped ==========
> 

and INSTALL target succeed too

> 1>  -- Install configuration: "Debug"
> 1>  -- Installing: full/path/to/jsoncpp/lib/pkgconfig/jsoncpp.pc
> 1>  -- Installing: full/path/to/jsoncpp/lib/jsoncpp.lib
> 1>  -- Installing: full/path/to/jsoncpp/include/jsoncpp/json/assertions.h
> 1>  -- Installing: full/path/to/jsoncpp/include/jsoncpp/json/autolink.h
> 1>  -- Installing: full/path/to/jsoncpp/include/jsoncpp/json/config.h
> 1>  -- Installing: full/path/to/jsoncpp/include/jsoncpp/json/features.h
> 1>  -- Installing: full/path/to/jsoncpp/include/jsoncpp/json/forwards.h
> 1>  -- Installing: full/path/to/jsoncpp/include/jsoncpp/json/json.h
> 1>  -- Installing: full/path/to/jsoncpp/include/jsoncpp/json/reader.h
> 1>  -- Installing: full/path/to/jsoncpp/include/jsoncpp/json/value.h
> 1>  -- Installing: full/path/to/jsoncpp/include/jsoncpp/json/version.h
> 1>  -- Installing: full/path/to/jsoncpp/include/jsoncpp/json/writer.h

but build failed with errors

> 3>ClCompile:
> 3>  b64.cpp
> 2>  crypto.cpp
> 3>  claims.cpp
> 3>  crypto.cpp
> 2>full\path\to\josepp/digest.hpp(48): error C3409: empty attribute block is not allowed
> 2>full\path\to\josepp/digest.hpp(48): error C2143: syntax error : missing ']' before '['
> 2>full\path\to\josepp/digest.hpp(48): error C2337: 'fallthrough' : attribute not found
> 2>full\path\to\josepp/digest.hpp(48): error C2143: syntax error : missing ';' before ']'
> 2>full\path\to\josepp/digest.hpp(49): warning C4482: nonstandard extension used: enum 'jose::digest::type' used in qualified name
> 2>full\path\to\josepp/digest.hpp(51): warning C4482: nonstandard extension used: enum 'jose::digest::type' used in qualified name
> 2>full\path\to\josepp/digest.hpp(53): warning C4482: nonstandard extension used: enum 'jose::digest::type' used in qualified name
> 2>full\path\to\josepp/sstring.hh(37): error C3646: 'noexcept' : unknown override specifier
> 2>full\path\toude\export\josepp/sstring.hh(50) : see reference to class template instantiation 'jose::secure_allocator<T>' being compiled
> 2>full\path\to\josepp/sstring.hh(37): error C2253: 'secure_allocator<T>' : pure specifier or abstract override specifier only allowed on virtual function
> 2>full\path\to\josepp/sstring.hh(39): error C3646: 'noexcept' : unknown override specifier
> 2>full\path\to\josepp/sstring.hh(44): error C3646: 'noexcept' : unknown override specifier
> 2>full\path\to\josepp/sstring.hh(46): error C3646: 'noexcept' : unknown override specifier
> 2>full\path\to\josepp/sstring.hh(52): error C2143: syntax error : missing ';' before '='
> 2>full\path\to\josepp/sstring.hh(52): error C2873: 'secure_string' : symbol cannot be used in a using-declaration
> 2>full\path\to\josepp/sstring.hh(52): error C2513: 'int' : no variable declared before '='
> 2>full\path\to\josepp/crypto.hpp(63): error C2873: 'password_cb' : symbol cannot be used in a using-declaration
> 2>full\path\to\josepp/crypto.hpp(63): error C2143: syntax error : missing ';' before '='
> 2>full\path\to\josepp/crypto.hpp(63): error C2065: 'secure_string' : undeclared identifier
> 2>full\path\to\josepp/crypto.hpp(63): error C2065: 'pass' : undeclared identifier
> 2>full\path\to\josepp/crypto.hpp(63): error C2062: type 'int' unexpected
> 2>full\path\to\josepp/crypto.hpp(66): error C2143: syntax error : missing ';' before '{'
> 
> 
> and ...

**Comment by troian** [comment]
Hi @souaremsaidou. This project does not have the official support of VS and I don't have any experience in using it as it has its own meaning of C++ standards. If you can make it PR is always welcome.

**Comment by souaremsaidou** [comment]
Hi @troian,

### About the PR
there's some fixes to do in CMakeLists.txt: 
- rework the pkg-config section 
- C++11 has no full support is VS 10 -> maybe upgrade to later version that support C++17+

### About the README
i think you should remove this line in yellow in the README file

![image](https://user-images.githubusercontent.com/57505334/75379626-00ed0380-58d6-11ea-9424-ba19bd1a834f.png)


BR,
Saidou

**Comment by troian** [comment]
@souaremsaidou ya, that confuses. I'll remove readme line
Meanwhile, all C++11 features should be compatible with C++17. Are not they?

**Comment by troian** [comment]
@souaremsaidou how you got any plans to make PR?

**Comment by souaremsaidou** [comment]
Hello, not yet.

BR,
Saidou

**Comment by troian** [comment]
Ok, closing the issue. Feel free to open a new one when have something to push
