### ISSUE TITLE
Unable to build on Mac. Cmake throws "package 'jsoncpp' not found"

### ISSUE THREAD

**Issue by staszain** [troian/jwtpp#33]
MacOS 10.15.4

tried installing with brew:
Error: No available formula with the name "jwtpp" 

tried building with Cmake:

cmake -Wno-dev -DCMAKE_TOOLCHAIN_FILE=/Users/xxxxx/Projects/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ ..

...
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/local/Cellar/openssl@1.1/1.1.1d/lib/libcrypto.dylib (found version "1.1.1d")
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Checking for module 'jsoncpp'
--   No package 'jsoncpp' found
CMake Error at /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPkgConfig.cmake:458 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPkgConfig.cmake:637 (_pkg_check_modules_internal)
  CMakeLists.txt:39 (pkg_check_modules)
-- Configuring incomplete, errors occurred!

jsoncpp is built with vcpkg as described in jsoncpp repo. tried installing it with brew as well.

**Comment by troian** [comment]
Thank you for reporting. brew formula is broken. I'll give a fix soon.
Regarding manual build, you have to install jsoncpp manually too.
`brew install jsoncpp` then try to build

**Comment by troian** [comment]
Tap fixed. `brew install jwtpp` is working now

**Comment by staszain** [comment]
I tried "brew install jsoncpp" yesterday. It doesn't work as well. I suspect it needs some additional variable or something, like openssl needs OPENSSL_ROOT_DIR to compile, but it is not transparent which one and where. Anyway, brew install jwtpp works now, thank you very much!

**Comment by staszain** [comment]
FYI, I'm afraid brew package is missing include folder after installation.

**Comment by troian** [comment]
@staszain could you describe more detailed? jwtpp provides pkg-config with includes dir in there

Yes. On MacOS you have to specify OPENSSL_ROOT_DIR on cmake stage.
For example `-DOPENSSL_ROOT_DIR=$(brew --prefix openssl)`
