### ISSUE TITLE
expire time verification?

### ISSUE THREAD

**Issue by ihmc3jn09hk** [troian/jwtpp#34]
Hi troian, thank you for the awesome work. May I have an example on how to control as well as perform a verification on the JWT expiration? I dont see an example in the `"tests/"` folder.

**Comment by troian** [comment]
Let me know if example below works for you. If not I'll make detailed example in the tests

```C++
	auto vf = [](jwtpp::sp_claims cl) {
		if (!cl->check().iss("issname")) {
			return false;
		}
		auto exp = cl->get().exp();
		// if exp is just UNIX timestamp then just compare with current time
	};

	EXPECT_TRUE(jws->verify(r256_pub, vf));
```

**Comment by ihmc3jn09hk** [comment]
> Let me know if example below works for you. If not I'll make detailed example in the tests
> 
> ```c++
> 	auto vf = [](jwtpp::sp_claims cl) {
> 		if (!cl->check().iss("issname")) {
> 			return false;
> 		}
> 		auto exp = cl->get().exp();
> 		// if exp is just UNIX timestamp then just compare with current time
> 	};
> 
> 	EXPECT_TRUE(jws->verify(r256_pub, vf));
> ```

Thanks, it's working

**Comment by troian** [comment]
Mind making PR to tests?

**Comment by ihmc3jn09hk** [comment]
> Mind making PR to tests?

Please check PR #35. Since I dont have GTest installed. I am not sure the code compiles at the moment.

**Comment by troian** [comment]
There is travic ci running. Will now soon.
